### ISSUE TITLE
Svg2ico running error

### ISSUE THREAD

**Issue by cnlinyuan** [ginopc/svg2ico#2]
Error :
Traceback (most recent call last):
  File "svg2ico.py", line 79, in <module>
    e.saveToFilename(args.o)
  File "svg2ico.py", line 60, in saveToFilename
    from PIL import Image
ImportError: No module named PIL

**Comment by ginopc** [comment]
What is OS?

**Comment by falsepopsky** [comment]
> 
> 
> What is OS?

i got the same problem, my os "windows 10" inkscape v 0.92

**Comment by ginopc** [comment]
Sorry but I'm working on upgrade this extension for Inkscape 1. There are a lot of changes, at this time, there isn't much time to do it.

**Comment by cnlinyuan** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maurizio Aru"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 下午4:51
收件人: "ginopc/svg2ico"<svg2ico@noreply.github.com&gt;; 
抄送: "LY"<339704677@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ginopc/svg2ico] Svg2ico running error (#2)





 
Sorry but I'm working on upgrade this extension for Inkscape 1. There are a lot of changes, at this time, there isn't much time to do it.

**Comment by ScribbleGhost** [comment]
https://github.com/ginopc/svg2ico/pull/7
