### ISSUE TITLE
How to use the extension after installing it?

### ISSUE THREAD

**Issue by max-hk** [ginopc/svg2ico#3]
I can't find svg2ico in the extension menu

**Comment by ferenk** [comment]
I tried to use it, too. I could find a new output format in the Save as... menu. Save as type: "Win Icon File (*.ico)"
However, I get an exception when I try to use it: "IOError: cannot identify image file 'C:\\Users\\FMoricz\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgAOUFJ0'".
I've checked it, the original SVG is copied to the correct path. Maybe the extension cannot recognize all types of SVG files? The original one was created with Inkscape.

**Comment by ginopc** [comment]
What is inkscape version you use?

**Comment by nikkiluzader** [comment]
I am having the same problem. here is my Inkscape version:

1.0 (4035a4fb49, 2020-05-01)



and here is the error:

Traceback (most recent call last):
  File "svg2ico.py", line 79, in <module>
    e.saveToFilename(args.o)
  File "svg2ico.py", line 61, in saveToFilename
    img = Image.open(self.ifName)
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file '/tmp/ink_ext_XXXXXX.svg6PJON0'


I am running this on Manjaro Cinnamon
![image](https://user-images.githubusercontent.com/35616227/86539017-a2f5ab80-bec7-11ea-9194-3a5e972a2efe.png)

**Comment by ginopc** [comment]
I'm work to upgrade extension for Inkscape v 1. There are many changes. Sorry for now

**Comment by hayden-flintoft** [comment]
Hi, this still seems to be an issue.

Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\inkscape\extensions\svg2ico\svg2ico.py", line 79, in <module>
    e.saveToFilename(args.o)
  File "C:\Users\****\AppData\Roaming\inkscape\extensions\svg2ico\svg2ico.py", line 61, in saveToFilename
    img = Image.open(self.ifName)
  File "C:\Program Files\Inkscape\lib\python3.10\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\****\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgFJRVS1'

Inkscape 1.2.1 (9c6d41e410, 2022-07-14)

Windows 11 

![image](https://user-images.githubusercontent.com/84941902/190933064-0c5112d7-af47-48a1-b231-9d93afd5c730.png)

**Comment by watkipet** [comment]
As @ginopc mentioned, version 0.2 of this extension isn't compatible with Inkscape 1.0 and later. I added issue #5 and pull request #6 to update the code for Inkscape 1.0.

**Comment by ScribbleGhost** [comment]
https://github.com/ginopc/svg2ico/pull/7
